`timescale 1ns/10ps

module top (
	sys_clk, 	//system clock, 200MHz clock generated by LO
	rst_n,		//power on reset, active low
	//sent/received to/from register file
	xbus_addr,	//address bus to access reg file
	xbus_din,	//data bus to access reg file
	xbus_dout,	//data bus from reg file
	xbus_wr,	//enable signal indicates read or write data to register file
	i_run_test_mode,//input signal indicates that usb chip is in test mode or not, 1-test mode, 0-normal mode
	i_otp_read_n,	//enable read mode of efuse controller, active low
	i_otp_prog,		//enable program mode of efuse controller
	//sent/received to/from otp memory
	o_otp_vddqsw,	//enable high voltage LDO for efuse programming, disable for read
	o_otp_csb,		//otp select enable, active low for programming/reading
	o_otp_strobe,	//output signal used to turn on the array for read/program access
	o_otp_load,		//output signal used to turn on sense amplifier (in otp mem) and load data into latch (in otp mem)
	i_otp_q,		//parallel data from efuse
	o_otp_addr,		//address access to otp mem
	o_otp_pgenb,	//program enable, active low
);

input sys_clk;
input rst_n;

output [6:0] xbus_addr;
output [7:0] xbus_din;
input [7:0] xbus_dout;
output xbus_wr;
input i_run_test_mode;
input i_otp_prog;
input i_otp_read_n;

output o_otp_vddqsw;
output o_otp_csb;
output o_otp_strobe;
output o_otp_load;
input [7:0] i_otp_q;
output o_otp_addr;
output o_otp_pgenb;

wire otp_busy_w;

// apb mux module
apb_mux apb_mux_i (
.i2c_busy			(),
.otp_busy			(otp_busy_w),
.i2c_xbus_addr		(),
.i2c_xbus_wr		(),
.i2c_xbus_din		(),
.i2c_xbus_dout		(),
.otp_xbus_addr		(otp_xbus_addr),
.otp_xbus_wr		(otp_xbus_wr),
.otp_xbus_din		(otp_xbus_din),
.otp_xbus_dout		(otp_xbus_dout),
.xbus_addr			(xbus_addr),
.xbus_wr			(xbus_wr),
.xbus_dout			(xbus_dout),
.xbus_din			(xbus_din),
.sys_clk			(sys_clk),
.rst_n				(rst_n)
);

// otp controller module
otp_main otp_main_i (
.sys_clk			(sys_clk),
.rst_n				(rst_n),
.i_i2c_busy			(i_i2c_busy),
.i_run_test_mode	(i_run_test_mode),
.o_otp_vddqsw		(o_otp_vddqsw),
.o_otp_csb			(o_otp_csb),
.o_otp_strobe		(o_otp_strobe),
.o_otp_load			(o_otp_load),
.i_otp_q			(i_otp_q),
.o_otp_addr			(o_otp_addr),
.o_otp_pgenb		(o_otp_pgenb),
.o_xbus_din			(otp_xbus_din),
.o_xbus_addr		(otp_xbus_addr),
.i_xbus_dout		(otp_xbus_dout),
.i_otp_read_n		(i_otp_read_n),
.i_otp_prog			(i_otp_prog),
.o_xbus_wr			(otp_xbus_wr),
.o_otp_busy			(otp_busy_w)
);

endmodule